name: .NET Run
# Trigger the workflow on push or pull request,
# but only for the main branch
on:   
  pull_request:
    branches:
    - main
    - master

jobs:
  BuildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: | 
        cd LinearAPI
        dotnet restore
    - name: Build
      run: | 
        cd LinearAPI
        dotnet build --no-restore
    - name: Run API
      run: | 
        dotnet run &
        sleep 5000
        output=$(curl -Is localhost:5000/healthcheck | grep HTTP | cut -d ' ' -f2)
        echo $output